### PR TITLE
Synchronize the YAML Log with spec

### PR DESCRIPTION
**Pull request by iherman**
Gregg,

I have modified the YAML output to bring it closer to what we discussed. Here is the current output for the simple example:

```yaml
- ca.2:
    log point: Entering the canonicalization function (4.5.3 (2)).
    with:
      - Bnode to quads:
          e0:
            - <http://example.com/#p> <http://example.com/#q> _:e0 .
            - _:e0 <http://example.com/#s> <http://example.com/#u> .
          e1:
            - <http://example.com/#p> <http://example.com/#r> _:e1 .
            - _:e1 <http://example.com/#t> <http://example.com/#u> .
- h1dg.1:
    log point: Entering Hash First Degree Quads function (4.7.3)
    with:
      - identifier: e0
- h1dg.1:
    log point: Entering Hash First Degree Quads function (4.7.3)
    with:
      - identifier: e1
- ca.3:
    log point: Calculated first degree hashes (4.5.3. (3)
    with:
      - Hash to bnodes:
          - hash: 21d1dd5ba21f3dee9d76c0c00c260fa6f5d5d65315099e553026f4828d0dc77a
            bnodes:
              - e0
          - hash: 6fa0b9bdb376852b5743ff39ca4cbf7ea14d34966b2828478fbf222e7c764473
            bnodes:
              - e1
- ca.4:
    log point: Canonicalization function (4.5.3 (4)).
    with:
      - identifier: e0
        hash: 21d1dd5ba21f3dee9d76c0c00c260fa6f5d5d65315099e553026f4828d0dc77a
        canonical id: c14n0
      - identifier: e1
        hash: 6fa0b9bdb376852b5743ff39ca4cbf7ea14d34966b2828478fbf222e7c764473
        canonical id: c14n1
- ca.5:
    log point: Calculate hashes for identifiers with shared hashes (4.5.3. (5)).
    with:
      - Hash to bnodes: []
- ca.6:
    log point: Leaving the canonicalization function (4.5.3)
    with:
      - issuer:
          issuer ID: "1235"
          prefix: c14n
          counter: "2"
          mappings:
            - e0=>c14n0
            - e1=>c14n1
```

### CODE REVIEW

**Comment by iherman** [comment]
ping @gkellogg

**Comment by gkellogg** [comment]
A couple of questions on this:

* h1dg.1 is called recursively from `ca.3.1`, but you show it before ca.3 and at the same level. Perhaps in this case being contained within `ca.3` isn't as important, as the further recursion is limited, but more generally, these algorithms can be recursive. Shouldn't it show up under `ca.3.1`?
* You use `with` consistently under each step. In some cases some property is needed to transition from a list to a map, but not everywhere. Also, is `with` intended to indicate the inputs to that step?
* in `ca.6`, you serialize the mappings such as `e0=>c14n0`, why not just use a map? A map would make each component more directly available.

**Comment by iherman** [comment]
> A couple of questions on this:
> 
> * h1dg.1 is called recursively from `ca.3.1`, but you show it before ca.3 and at the same level. Perhaps in this case being contained within `ca.3` isn't as important, as the further recursion is limited, but more generally, these algorithms can be recursive. Shouldn't it show up under `ca.3.1`?

I will have to look at this. The current version puts out a flat sequence of logs, it does not follow the recursions. Following the recursive levels may force me to do some more surgery on the code; at present, the log calls are really just a beefed up versions of console.log calls. 

> * You use `with` consistently under each step. In some cases some property is needed to transition from a list to a map, but not everywhere. Also, is `with` intended to indicate the inputs to that step?

I saw your example, and you realized the answer... but yes, essentially, the 'with' gives the set of arguments to the calls.

> * in `ca.6`, you serialize the mappings such as `e0=>c14n0`, why not just use a map? A map would make each component more directly available.

That is a leftover of the non-yaml world :-).

**Comment by iherman** [comment]
The log looks like this now:

```yaml
ca:
  - ca.2:
      log point: Entering the canonicalization function (4.5.3 (2)).
      with:
        - Bnode to quads:
            e0:
              - <http://example.com/#p> <http://example.com/#q> _:e0 .
              - _:e0 <http://example.com/#s> <http://example.com/#u> .
            e1:
              - <http://example.com/#p> <http://example.com/#r> _:e1 .
              - _:e1 <http://example.com/#t> <http://example.com/#u> .
  - ca.3:
      - ca.3.1:
          - h1dg:
              - h1dg.1:
                  log point: Entering Hash First Degree Quads function (4.7.3)
                  with:
                    - identifier: e0
              - h1dg.5:
                  log point: Leaving Hash First Degree Quads function (4.7.3).
                  with:
                    - identifier: e0
                      quads:
                        - <http://example.com/#p> <http://example.com/#q> _:a .
                        - _:a <http://example.com/#s> <http://example.com/#u> .
                      hash: 21d1dd5ba21f3dee9d76c0c00c260fa6f5d5d65315099e553026f4828d0dc77a
          - h1dg:
              - h1dg.1:
                  log point: Entering Hash First Degree Quads function (4.7.3)
                  with:
                    - identifier: e1
              - h1dg.5:
                  log point: Leaving Hash First Degree Quads function (4.7.3).
                  with:
                    - identifier: e1
                      quads:
                        - <http://example.com/#p> <http://example.com/#r> _:a .
                        - _:a <http://example.com/#t> <http://example.com/#u> .
                      hash: 6fa0b9bdb376852b5743ff39ca4cbf7ea14d34966b2828478fbf222e7c764473
      - ca.3.2:
          log point: Calculated first degree hashes (4.5.3. (3))
          with:
            - Hash to bnodes:
                - hash: 21d1dd5ba21f3dee9d76c0c00c260fa6f5d5d65315099e553026f4828d0dc77a
                  bnodes:
                    - e0
                - hash: 6fa0b9bdb376852b5743ff39ca4cbf7ea14d34966b2828478fbf222e7c764473
                  bnodes:
                    - e1
  - ca.4:
      log point: Canonicalization function (4.5.3 (4)).
      with:
        - identifier: e0
          hash: 21d1dd5ba21f3dee9d76c0c00c260fa6f5d5d65315099e553026f4828d0dc77a
          canonical id: c14n0
        - identifier: e1
          hash: 6fa0b9bdb376852b5743ff39ca4cbf7ea14d34966b2828478fbf222e7c764473
          canonical id: c14n1
  - ca.5:
      - push info: Calculate hashes for identifiers with shared hashes (4.5.3. (5)).
      - ca.5.extra:
          with:
            - Hash to bnodes: []
  - ca.6:
      log point: Leaving the canonicalization function (4.5.3)
      with:
        - issuer:
            issuer ID: "1235"
            prefix: c14n
            counter: "2"
            mappings:
              e0: c14n0
              e1: c14n1
```

I will merge the PR, though I am sure more can be done...

**Pull request merged**
